[package]
name = "hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
bs58 = "0.5.1"
solana-sdk = "2.3.1"
spl-token = "8.0.0"
base64 = "0.22.1"